send_command:
  name: Send command
  description: Send a command to a specific OpenShock shocker.
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: openshock
    shocker_id:
      required: false
      selector:
        text:
    command:
      required: true
      selector:
        select:
          options:
            - shock
            - vibrate
            - sound
            - stop
    intensity:
      required: false
      selector:
        number:
          min: 1
          max: 100
          mode: slider
    duration_ms:
      required: false
      selector:
        number:
          min: 300
          max: 30000
          step: 100
          mode: box

stop_all:
  name: Stop all
  description: Send an immediate stop command to all OpenShock shockers.
